name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use Eclipse Temurin distribution

      # Step 3: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1 # Replace with the desired Flutter version

      # Step 4: Cache dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.workspace }}/.pub-cache
            build
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}

      # Step 5: Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 6: Build APK
      - name: Build release APKs (split per ABI)
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      # Step 7: Upload APK artifacts
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apks
          path: build/app/outputs/flutter-apk/*.apk
